# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('local', models.CharField(max_length=200, verbose_name='local')),
                ('email', models.EmailField(max_length=100, verbose_name='e-mail')),
            ],
        ),
    ]
